In [1]:
import numpy as np
import pandas as pd
import requests

In [32]:
salary_df = pd.read_csv("nhl_salaries.csv")
skaters_df = pd.read_csv("eh_skater_data_3_14.csv")
goalies_df = pd.read_csv("eh_goalie_data_3_14.csv")
players_dk = pd.read_csv("DKSalaries_3_14.csv")

In [70]:
g = goalies_df[["Player", "GP"]]
t = skaters_df[["Player", "GP"]]

players_games_played = t.append(g)

total_player_data = pd.merge(left=players_dk, right=players_games_played, left_on='Name', right_on='Player')
total_player_data.head()

          Player  GP
0   Aaron Ekblad  27
1   Adam Boqvist  18
2      Adam Erne  20
3       Adam Fox  26
4  Adam Gaudette  27

In [74]:
total_player_data = pd.merge(left=players_dk, right=players_games_played, left_on='Name', right_on='Player')
total_player_data.head()

,Position,Name + ID,Name,ID,Roster Position,Salary,Game Info,TeamAbbrev,AvgPointsPerGame,player_name_clean,Player,GP
0,C,Auston Matthews (16667371),Auston Matthews,16667371,C/UTIL,9300,TOR@OTT 03/14/2021 07:00PM ET,TOR,19.00,AustonMatthews,Auston Matthews,26
1,C,Nathan MacKinnon (16667373),Nathan MacKinnon,16667373,C/UTIL,8900,LA@COL 03/14/2021 05:30PM ET,COL,14.90,NathanMacKinnon,Nathan MacKinnon,21
2,G,Frederik Andersen (16668143),Frederik Andersen,16668143,G,8500,TOR@OTT 03/14/2021 07:00PM ET,TOR,11.94,FrederikAndersen,Frederik Andersen,21
3,G,Jack Campbell (16668144),Jack Campbell,16668144,G,8500,TOR@OTT 03/14/2021 07:00PM ET,TOR,20.87,JackCampbell,Jack Campbell,3
4,G,James Reimer (16668145),James Reimer,16668145,G,8400,CAR@DET 03/14/2021 05:00PM ET,CAR,14.49,JamesReimer,James Reimer,15

In [72]:
t_merge.shape

(245, 12)

In [17]:
salary_df.head()
players_dk["player_name_clean"] = salary_df.Player_clean.str.replace(" ", "")

skaters_df.head()
skaters_df["player_name_clean"] = skaters_df.Player.str.replace(" ", "")

merge = pd.merge(left=players_dk, right=skaters_df, left_on='player_name_clean', right_on='player_name_clean')

In [29]:
#skaters_df.head()
merge.head()

test = merge[["Name", "Roster Position", "Salary", "AvgPointsPerGame", "GP"]]

print(test.shape)

test = test.loc[(test['GP']>=3)]

print(test.shape)
test.head()

(326, 5)
(326, 5)

                Name Roster Position  Salary  AvgPointsPerGame  GP
0    Auston Matthews          C/UTIL    9300             19.00  20
1   Nathan MacKinnon          C/UTIL    8900             14.90  14
2  Frederik Andersen               G    8500             11.94  18
3      Jack Campbell               G    8500             20.87  13
4       James Reimer               G    8400             14.49  16

In [4]:
merge = pd.merge(left=salary_df, right=skaters_df, left_on='player_name_clean', right_on='player_name_clean')

In [11]:
merge.head()

,PLAYER,Player_clean,CAP HIT,SALARY,player_name_clean,Player,Season,Team,Position,GP,...,iHF,iHA,iPENT2,iPEND2,iPENT5,iPEND5,iPEN±,FOW,FOL,FO±
0,1. Connor McDavid,Connor McDavid,12500000,14000000,ConnorMcDavid,Connor McDavid,20-21,EDM,C,20,...,21,30,6,15,0,0,9,127,127,0
1,2. Artemi Panarin,Artemi Panarin,11642857,13000000,ArtemiPanarin,Artemi Panarin,20-21,NYR,C,14,...,5,8,0,2,0,0,2,0,1,-1
2,3. Auston Matthews,Auston Matthews,11640250,15900000,AustonMatthews,Auston Matthews,20-21,TOR,C,18,...,22,20,1,5,0,0,4,168,147,21
3,4. Erik Karlsson,Erik Karlsson,11500000,12000000,ErikKarlsson,Erik Karlsson,20-21,S.J,D,13,...,5,19,1,2,0,0,1,0,0,0
4,5. Drew Doughty,Drew Doughty,11000000,10000000,DrewDoughty,Drew Doughty,20-21,L.A,D,16,...,21,25,4,1,0,0,-3,0,0,0

In [10]:
dat = merge.drop(columns=['PLAYER', 'Player_clean', 'SALARY', 'player_name_clean', 'Season'])

dat["cap_hit_clean"] = dat["CAP HIT"].str.replace("$", "")
dat["cap_hit_clean"] = dat["cap_hit_clean"].str.replace(",","")


dat.astype({'cap_hit_clean': 'int64'}).dtypes

dat_test = dat[["Player"]]

dat.head()

,CAP HIT,Player,Team,Position,GP,TOI,G,A1,A2,Points,...,iHA,iPENT2,iPEND2,iPENT5,iPEND5,iPEN±,FOW,FOL,FO±,cap_hit_clean
0,12500000,Connor McDavid,EDM,C,20,445.78,12,17,8,37,...,30,6,15,0,0,9,127,127,0,12500000
1,11642857,Artemi Panarin,NYR,C,14,288.50,5,8,5,18,...,8,0,2,0,0,2,0,1,-1,11642857
2,11640250,Auston Matthews,TOR,C,18,391.48,18,6,5,29,...,20,1,5,0,0,4,168,147,21,11640250
3,11500000,Erik Karlsson,S.J,D,13,332.82,0,1,3,4,...,19,1,2,0,0,1,0,0,0,11500000
4,11000000,Drew Doughty,L.A,D,16,423.73,4,3,8,15,...,25,4,1,0,0,-3,0,0,0,11000000

In [137]:
def test_build(players, budget, inc, limits):
    
    ## first we divide all working money sums by the increment
    budget = int(budget / inc)
    for player in players:
        player[1] = int(int(player[1]) / inc)
    
    nPlayers = len(players) 
    
    combos = {}
    combos_traceback = {}
    
    for forwards in range(limits["C"] + 1):
        for right_wings in range(limits["R"] + 1):
            for left_wings in range(limits["L"] + 1):
                for defense in range(limits["D"] + 1):
                    for goalies in range(limits["G"] + 1):
                        combos[(forwards, right_wings, left_wings, defense, goalies)] = [[-1 for i in range(budget + 1)] for i in range(nPlayers + 1)]
                        combos_traceback[(forwards, right_wings, left_wings, defense, goalies)] = [[None for i in range(budget + 1)] for i in range(nPlayers + 1)]
                
                
    ## First, fill in the base case for 0 forwards, defenders, and goalies
    combos[(0,0,0)] = [[-0 for i in range(budget + 1)] for i in range(nPlayers + 1)]
    
    ## Now we iterate through the combinations of forwards, defenders, and goalies
    for forwards in range(limits["C"] + 1):
        for right_wings in range(limits["R"] + 1):
            for left_wings in range(limits["L"] + 1):
                for defense in range(limits["D"] + 1):
                    for goalies in range(limits["G"] + 1):
                
                
                        roster_limits = {"C":forwards,"R": right_wings ,"L":left_wings ,"D": defense, "G":goalies}
                        table = combos[(forwards, right_wings, left_wings, defense, goalies)]
                        traceback = combos_traceback[(forwards, right_wings, left_wings, defense, goalies)]
                
                        ## Filling in the base case for 0 players to choose from
                        for i in range(budget + 1):
                            table[0][i] = 0
                    
                        ## Now we incrememnt through each player
                        for player_row in range(1, nPlayers + 1):
                    
                            ## For each player, we increment through our budget
                            for budget_interval in range(budget + 1):
                        
                                ##For each acceptable player, we see if we can afford the player and if we have roster space
                                player_position = players[player_row -1][3]
                                if roster_limits[player_position] > 0 and budget_interval >= players[player_row - 1][1]:
                    
                    
                                    ## We calculate the points
                                    points = players[player_row - 1][2]
                        
                                    ## We look through previous dictionarys to find the rest of the ROI
                                    if player_position == "C":
                                        restOfROI = combos[(forwards - 1, right_wings, left_wings, defense, goalies)][player_row - 1][budget_interval - players[player_row - 1][1]]
                                    elif player_position == "R":
                                        restOfROI = combos[(forwards, right_wings -1 , left_wings, defense, goalies)][player_row - 1][budget_interval - players[player_row - 1][1]]
                                    elif player_position == "L":
                                        restOfROI = combos[(forwards, right_wings, left_wings - 1, defense, goalies)][player_row - 1][budget_interval - players[player_row - 1][1]]
                                    elif player_position == "D":
                                        restOfROI = combos[(forwards, right_wings, left_wings, defense - 1, goalies)][player_row - 1][budget_interval - players[player_row - 1][1]]
                                    elif player_position == "G":
                                        restOfROI = combos[(forwards, right_wings, left_wings, defense, goalies - 1)][player_row - 1][budget_interval - players[player_row - 1][1]]
                                        
                                    ## We compare it for the optimal value if we dont sign the player
                                    noSign = table[player_row - 1][budget_interval]
                
                                    ## if signing the player generates more profit than not signing the player, then we add him to the table
                                    if points + restOfROI > noSign:
                                        table[player_row][budget_interval] = points + restOfROI
                                        traceback[player_row][budget_interval] = True
                                
                                    else:
                                        table[player_row][budget_interval] = noSign
                                        traceback[player_row][budget_interval] = False
                                
                                ## if we cant afford the player or have roster room, we treat it as a noSign
                                else:
                                    table[player_row][budget_interval] = table[player_row - 1][budget_interval]
                                    traceback[player_row][budget_interval] = False
                            
    ## To return the optimized investment portfolio, we create an empty return list
    ## and initialize our item marker value, and a money iteration value
    ret_list = []
    val = nPlayers
    i = -1
    forwards = limits["C"]
    right_wings = limits["R"]
    left_wings = limits["L"]
    defense = limits["D"]
    goalies = limits["G"]
    
    ## we loop through our table until our value (signifying the current item) is at 0
    while val > 0:
        
        ## If our traceback table tells us to buy the investment
        if combos_traceback[(forwards, right_wings, left_wings, defense, goalies)][val][i]:
            
            ## We record the player position
            player_position = players[val - 1][3]
            
            ## We add our investment number, cost, and ROI to our output list
            ret_list.append((players[val - 1][0], players[val - 1][1] * inc, players[val - 1][2], players[val - 1][3]))
            
                            
            ## We increment our money iteration value backwards by the amount that we "spent" on the investment
            ## And increment our item marker value back by 1
            ## and incrememnt back the roster space
            i -= players[val - 1][1]
            val -= 1
            
            if player_position == "C":
                forwards -= 1
            if player_position == "R":
                right_wings -= 1    
            if player_position == "L":
                left_wings -= 1
            elif player_position == "D":
                defense -= 1
            elif player_position == "G":
                goalies -= 1
        
        ## If our traceback table tells us to not buy the investment,
        ## we simply increment our item marker value back by 1
        else:
            val -= 1
    
    
    return ret_list, combos, combos_traceback

In [138]:
dat.head()
data_for_algo = dat[["Player", "cap_hit_clean", "Points", "Position"]].values.tolist()

In [139]:
data_for_algo[1]

['Artemi Panarin', '11642857', 18, 'C']

In [140]:
limits = {"C": 4,"R": 4 ,"L" : 4,"D": 6, "G": 0}
results = test_build(data_for_algo, 81500000, 100000, limits)

In [ ]:
results[0]

In [ ]:
for i in